# punjabi wordlist
# -------------------------------------------------------
# mostly from Fluent Forever's list of 625 most common concrete nouns/verbs
#  - (I added a few of my own words here as I went along)
# lpssme: learn punjabi: sentence structure made easy
# -------------------------------------------------------
# **  means it's a duplicate or something. probably don't make card
# ?? means need help with translation or something.
# ^^ means go back and capitalize after merging all lists


* ਤੀਰਅੰਦਾਜ਼ (adjectives)
long, ਲੰਬਾ laṇbā :ff625:lpssme: # also means tall
short (a),[vs long] ਛੋਟਾ  ??
tall, ਲੰਬਾ laṇbā :lpssme: # also means long
short (a),[vs tall] ਛੋਟਾ ??
wide (a),ਚੌੜਾ
narrow (a),ਸੌੜਾ
big/large (a), ਵੱਡਾ vaḍḍā :ff625:lpssme:
small/short, ਛੋਟਾ choṭā :ff625:lpssme:
slow (a),ਹੌਲੀ
fast,ਤੇਜ਼
hot (n),ਗਰਮ  # same as warm
cold (a),ਠੰਡੇ # same as cool
warm (a),ਗਰਮ # same as hot
cool (a),ਠੰਡਾ    # same as cold **
new (a), ਨਵਾਂ nawāṇ :ff625:lpssme:
old [vs new] (a), ਪੁਰਾਣਾ purāṇā :ff625:lpssme:
young (a),ਨੌਜਵਾਨ
old [vs young] (a),  ਬਿਰਧ  ??
good (a), ਚੰਗਾ caṇgā :ff625:lpssme:
bad, ਬੁਰਾ burā :lpssme:  # also ਮੰਦਾ ?
wet (a),ਭਿੱਜ  # ?? bhi/jna seems to mean "to get drenched"
dry (a),ਸੁੱਕੀ
sick (a),ਬਿਮਾਰ
healthy (a),ਸਿਹਤਮੰਦ
loud (a),ਉੱਚੀ
quiet (a),ਸ਼ਾਂਤ
happy (a), ਖੁਸ਼ kush :ff625:lpssme:
sad (a),ਉਦਾਸ
beautiful, ਸੋਹਣਾ sohṇā :lpssme: # also ਸੁੰਦਰ **
ugly (a),ਬਦਸੂਰਤ
deaf (a),ਬੋਲ਼ੇ
blind (a),ਅੰਨਹੇ / ਅੰਨ੍ਹੇ
nice (a),ਚੰਗੇ
mean (/nice),ਅਸਲ
rich (a),ਅਮੀਰ
poor (n),ਗਰੀਬ
thick (a),ਮੋਟਾ # ** same as fat
thin (a). ਪਤਲੇ
expensive (a),ਮਹਿੰਗਾ
cheap,ਸਸਤੇ
flat (a), # ???  **
curved (a),ਵਕਰ
male (a),ਪੁਲਿੰਗ
female (a),ਮਾਦਾ
tight (a),ਤੰਗ
loose (a),ਢਿੱਲੀ
high (a),ਉੱਚ
low (a),ਘੱਟ  ?? **
soft (a),ਕੋਮਲ  # ?? ਨਰਮ ?
hard [vs soft] (a), ਸਖਤ
hard [difficult], ਔਖਾ aukhā :ff625:lpssme:
deep (a),ਡੂੰਘੇ
shallow (a),ਖੋਖਲਾ ??gt
dirty (a),ਗੰਦੇ
strong (a),ਮਜ਼ਬੂਤ
weak (a),ਕਮਜ਼ੋਰ
dead (a),ਮਰੇ
alive,ਜਿੰਦਾ
heavy (a),ਭਾਰਾ
light (a) [vs heavy],ਹਲਕਾ ??
dark (a),ਹਨੇਰ
light (a) [vs dark],ਹਲਕਾ ??
nuclear (a),ਨਿਊਕਲੀ
famous (a),ਮਸ਼ਹੂਰ

* ਜਾਨਵਰ (animals)
dog (n),ਕੁੱਤਾ
cat, ਬਿੱਲੀ billī :ff625:lpssme:
fish (n),ਮੱਛੀ
bird,ਪੰਛੀ
cow (n),ਗਊ
pig (n),ਸੂਰ
mouse (n),ਚੂਹਾ
horse (n),ਘੋੜਾ
wing (n) ਖੰਭ # ਵਿੰਗ ?? dict says ਖੰਭ but gt translates this as "feathers". however, wings->khanbh
animal (c),ਜਾਨਵਰ

* ਕਲਾ (art)
band [music] (n),? ਵਾਜੇ ਵਾਲਾ
song(s) (n), ਗੀਤ gīt :lpssme:
instrument [musical] (n),ਸੰਗੀਤ ਸਾਧਨ
music (n),ਸੰਗੀਤ
movie/film, ਫਿਲਮ film :ff625:lpssme:
art (c),ਕਲਾ

* ਪੀਨਾ (beverages)
coffee (n),ਕਾਫੀ
tea (n), ਚਾਹ
wine (n), ਸ਼ਰਾਬ
beer,ਬੀਅਰ  # ??
juice (n),ਜੂਸ # ??
water, ਪਾਣੀ pāṇī :ff625:lpssme:
milk (n),ਦੁੱਧ
beverage,ਪੀਨਾ or ਕੋਲਡਢਰੀਨਕ (colddrink)


* ਸਰੀਰ (body)
head (n),ਸਿਰ
neck (n),ਗਰਦਨ
face (n),ਚਿਹਰਾ
beard,ਦਾੜ੍ਹੀ
hair (n),ਵਾਲ
eye (n),ਅੱਖ
mouth (n),ਮੂੰਹ
lip (n),ਹੋਠ
nose (n),ਨੱਕ
tooth (n),ਦੰਦ
ear (n),ਕੰਨ
tear (n) [teardrop], ਅੱਥਰੂ
tongue (n),ਜੀਭ
back [body], ਪੀਥ  ??
toe (n) ਅੰਗੂਠੇ
finger(n),ਉਂਗਲ
foot [body] (n),ਪੈਰ
hand (n),ਹੱਥ
leg (n),ਲੱਤ
arm,ਆਰਮ ਬਾਹ
shoulder (n), ਮੋਢੇ
heart (n),ਦਿਲ
blood,ਬਲੱਡ
brain,ਦਿਮਾਗ
knee (n),ਗੋਡਾ
sweat (n),ਪਸੀਨਾ
disease (n),ਬਿਮਾਰੀ
bone,ਹੱਡੀ
voice (n),ਆਵਾਜ਼
skin (n),ਚਮੜੀ
body,ਸਰੀਰ

* ਪੁਸ਼ਾਕ (clothing)
hat (n),ਟੋਪੀ
dress (n), ??
suit (n),ਸੂਟ ??
skirt (n),ਸਕਰਟ
shirt (n),ਕਮੀਜ਼
t-shirt,ਟੀ-ਸ਼ਰਟ ^^
pants (n),ਪੈਂਟ
shoes (n), ਜੁੱਤੀਆਂ juttīāṇ :ff625:lpssme:
pocket (n),ਜੇਬ
coat (n),ਕੋਟ
stain (n),ਦਾਗ਼  # ** ਵੱਟਾ  ??
clothing (c),ਪੁਸ਼ਾਕ
clothes (n), ਕੱਪੜੇ kappr̥e :lpssme:

* ਰੰਗ (colors)
red,ਲਾਲ
green(a),ਹਰਾ
blue,ਨੀਲਾ
yellow (n),ਪੀਲਾ
brown,ਭੂਰਾ
pink (a),ਗੁਲਾਬੀ
orange [color],ਸੰਤਰਾ ਰੰਗ
black,ਕਾਲਾ
white (a), ਚਿੱਟਾ
gray (a),ਸਲੇਟ
color (n),ਰੰਗ


* ਹਫ਼ਤੇ ਦੇ ਦਿਨ (days of the week)
monday (n),ਸੋਮਵਾਰ ^^
tuesday (n), ਮੰਗਲਵਾਰ^^
wednesday (n),ਬੁੱਧਵਾਰ ^^
thursday (n), ਵੀਰਵਾਰ ^^
friday,ਸ਼ੁੱਕਰਵਾਰ ^^
saturday (n),ਸ਼ਨੀਵਾਰ ^^
sunday (n),ਸੋਮਵਾਰ  ^^

* ਦਿਸ਼ਾਵਾਂ (directions)
top (n), ਸਿਖਰ
bottom,ਤਲ
side (n),ਪਾਸੇ
front (n),ਅੱਗੇ
back [direction],ਵਾਪਸ
outside (a),ਬਾਹਰ
inside (a),ਅੰਦਰ
up (n),ਉੱਤੇ  # ?? go up -> ute jao
down (a),ਥੱਲੇ
left [direction],ਖੱਬੇ
right [direction],ਸੱਜੇ
straight [direction], ਸਿੱਧਾ ??
north,ਉੱਤਰ
south (a),ਦੱਖਣ
east (n),ਪੂਰਬ
west (n),ਪੱਛਮ
direction (c),ਦਿਸ਼ਾ

* electronics
electronics,??
clock (n),ਘੜੀ
lamp (n),ਲੈਂਪ
fan [electronics] (n),ਬਿਜਲੀ ਪੱਖੀ
cell phone,ਫ਼ਨ
network (n),ਨੈਟਵਰਕ
computer (n),ਕੰਪਿਊਟਰ
program (computer),ਪ੍ਰੋਗ੍ਰਾਮ ?
laptop (n),ਲੈਪਟਾਪ
screen (n), ਪਰਦਾ  ?? ਸਕ੍ਰੀਨ ?
camera,ਕੈਮਰਾ
television (n), ਟੈਲੀਵਿਜ਼ਨ
radio (n),ਰੇਡੀਓ

* ਭੋਜਨ (foods)
egg (n),ਅੰਡੇ
cheese,ਪਨੀਰ
bread (n), ਰੋਟੀ roṭī :ff625:lpssme:
soup (n),ਸੂਪ
cake,ਕੇਕ
chicken,ਮੁਰਗੇ
pork (n),ਸੂਰ ਦਾ ਮਾਸ
beef,ਬੀਫ or ਮਾਜ ਦਾ ਮੀਟ
apple,ਸੇਬ
banana,ਕੇਲਾ
orange (food),ਸੰਤਰਾ
lemon (n),ਨਿੰਬੂ
corn (n),ਮਕਈ
rice (n),ਚੌਲ
oil (n),ਤੇਲ
seed (n),ਬੀਜ
knife (n),ਚਾਕੂ
spoon (n),ਚਮਚਾ
fork (n),ਕਾਂਟਾ
plate (n),ਪਲੇਟ
cup (n),ਕੱਪ
breakfast,ਨਾਸ਼ਤਾ
lunch (n),ਦੁਪਹਿਰ ਦਾ ਖਾਣਾ
dinner (n),ਰਾਤ ਦੀ ਰੋਟੀ
sugar (n),ਖੰਡ
salt (n),ਲੂਣ
bottle,ਬੋਤਲ
food/meal(s) (n), ਭੋਜਨ bhojan :ff625:lpssme:

* home
table (n),ਮੇਜ਼
chair (n), ਕੁਰਸੀ kursī :ff625:lpssme:
bed,ਮੰਜੇ
dream (n),ਸੁਪਨੇ
window (n), ?? dictionary: ਤਕੀ  gt: ਵਿੰਡੋ
door (n), ਦਰਵਾਜ਼ਾ darwāzā :ff625:lpssme:
bedroom,ਬੈੱਡਰੂਮ   or ਸੌਨ ਵਾਲਾ ਕਮਰਾ
kitchen (n),ਰਸੋਈ
pencil (n),ਪੈਨਸਿਲ
pen (n),ਕਲਮ
photograph (n),ਫੋਟੋ
soap (n),ਸਾਬਣ
book, ਕਿਤਾਬ kitāb :ff625:lpssme:
page (n),ਪੰਨਾ
key (n),ਚਾਬੀ
paint (n),ਪੇਂਟ
letter (n),ਚਿੱਠੀ
note (on paper),ਨੋਟ
wall (n),ਕੰਧ
paper (n),ਪੇਪਰ ?
floor (n),ਮੰਜ਼ਲ
ceiling,ਛੱਤ  # ?? same as roof??
roof (n),ਛੱਤ  # ?? same as ceiling??
pool (n),ਸਵਿਮਿੰਗ ਪੂਲ
lock (n),ਲਾਕ  ???
telephone (n),ਟੈਲੀਫੋਨ ??
garden,ਬਾਗ਼
yard [of a house] (n), ਯਾਰਡ # dictionary: gaz?
needle (n),ਸੂਈ
bag (n),ਲਫਾਫਾ
box (n),ਬਾਕਸ
gift, ਤੋਹਫ਼ੇ tohfe :ff625:lpssme:
card,ਕਾਰਡ
ring (n),ਮੁੰਦਰੀ  # ?? really? gt says wedding ring = ਵਿਆਹ ਦੀ ਰਿੰਗ
tool (n),ਸੰਦ   # ?? ਟੂਲ

* ਨੌਕਰੀ (jobs)
teacher (n),ਅਧਿਆਪਕ
student (n),ਵਿਦਿਆਰਥੀ
lawyer (n),ਵਕੀਲ
doctor (n),ਡਾਕਟਰ
patient [hospital] (n),ਮਰੀਜ਼
waiter (n),ਬਹਿਰਾ
secretary (n),ਸਕੱਤਰ
priest (n),ਪਾਦਰੀ
police (n),ਪੁਲਿਸ
army,ਫ਼ੌਜੀ
soldier (n),ਸਿਪਾਹੀ
artist,ਕਲਾਕਾਰ
author (n),ਲੇਖਕ
manager (n),ਪ੍ਰਬੰਧਕ
reporter (n),ਰਿਪੋਰਟਰ
actor,ਅਭਿਨੇਤਾ
job (n),ਨੌਕਰੀ

* locations
city,ਸ਼ਹਿਰ
house(s) (n), ਘਰ ghar :ff625:lpssme:
apartment,ਮਕਾਨ
street/road (n),ਸੜਕ
airport,ਹਵਾਈ ਅੱਡੇ
train station (n),ਰੇਲਵੇ ਸਟੇਸ਼ਨ
bridge (n),ਪੁਲ
hotel (n),ਹੋਟਲ
restaurant (n),ਭੋਜਨਾਲਾ
farm (n),ਖੇਤ
court (n),ਅਦਾਲਤ
school (n),ਸਕੂਲ
office (n),ਦਫਤਰ
room [in a house] (n), ਕਮਰਾ kamrā :ff625:lpssme:
town (n),ਸ਼ਹਿਰ # same as city :(
university (n),ਯੂਨੀਵਰਸਿਟੀ ??
club (location), # ??
bar (location),ਠੈਕਾ
park (location) (n),ਪਾਰਕ
camp (n),ਡੇਰੇ
store/shop (n),ਦੁਕਾਨ
theater (n),ਥੀਏਟਰ
library (n),ਪੁਸਤਕਾਲਾ
hospital (n),ਹਸਪਤਾਲ
church,ਚਰਚ
market (n),ਮੰਡੀ
country [nation] (n),ਦੇਸ਼
building,ਇਮਾਰਤ
ground(n),ਜ਼ਮੀਨ
space (n)[outer space], ਸਪੇਸ
bank,ਬੇੰਕ (account: ਖਾਤਾ)
location (place),ਸਥਾਨ

* ਸਮੱਗਰੀ (materials)
glass (n),ਗਲਾਸ
metal (n),ਧਾਤੂ
plastic (n),ਪਲਾਸਟਿਕ ?
wood (n),ਲੱਕੜ
stone (n),ਪੱਥਰ
diamond (n),ਹੀਰਾ
clay,ਮਿੱਟਾ
dust (n),ਧੂੜ
earth (n),ਧਰਤੀ
gold (n),ਸੋਨਾ
copper (n),ਤਾਂਬਾ
silver (n), ਚਾਂਦੀ
material (n),ਸਮੱਗਰੀ

* math/measurements
meter (n),ਮੀਟਰ
centimeter,??
kilogram (n),ਕਿਲੋਗ੍ਰਾਮ
inch (n),ਇੰਚ
foot (measurement) **
pound (weight),ਪਾਉਂਡ
half (n),ਅੱਧੇ
circle (n),ਚੱਕਰ
square (n),ਵਰਗ
temperature (n), ਤਾਪਮਾਨ
date (n),ਤਾਰੀਖ  # (ex: May 7)
weight [measurement] (n),ਭਾਰ # ??
edge (n),ਕਿਨਾਰੇ
corner (n),ਨੁੱਕਰ

* misc nouns
map (n),ਨਕਸ਼ਾ
dot (n),ਬਿੰਦੀ
consonant (n),ਵਿਅੰਜਨ
vowel (n),ਸਵਰ
light (n),ਜੋਤ
sound (n),ਆਵਾਜ਼
yes (n),ਹਾਂ
no,ਨਹੀਂ
piece (n),ਟੁਕੜਾ
pain (n),ਦਰਦ
injury (n),ਸੱਟ
hole (n),ਮੋਰੀ
image (n),ਰੂਪ    # ?? "form"
pattern (n),ਨਮੂਨਾ
noun (n), ਨਾਮ
verb (n), ਕਿਰਿਆ
adjective,ਤੀਰਅੰਦਾਜ਼

* months
january (n),ਜਨਵਰੀ ^^
february,ਫਰਵਰੀ ^^
march (n),ਮਾਰਚ ^^
April,ਅਪ੍ਰੈਲ ^^
may (n),ਮਈ ^^
june (n),ਜੂਨ ^^
july (n),ਜੁਲਾਈ ^^
august,ਅਗਸਤ ^^
september (n), ਸਤੰਬਰ ^^
october (n),ਅਕਤੂਬਰ ^^
november,ਨਵੰਬਰ ^^
december,ਦਸੰਬਰ ^^

* nature
sea (n),ਸਮੁੰਦਰ   / same word as ocean **
ocean (n),ਸਮੁੰਦਰ
river (n),ਨਦੀ
mountain (n),ਪਹਾੜ
rain (n), ਮੀਂਹ mīṇh :ff625:lpssme:  # ** also ਵਰਖਾ, ਬਾਰਿਸ਼
snow/ice (n), ਬਰਫ਼ barf :lpssme:  # ** ਹਿਮ also means snow?
tree (n),ਰੁੱਖ
sun (n),ਸੂਰਜ
moon (n),ਚੰਦ
world (n), ਸੰਸਾਰ
Earth [planet]
forest (n),ਜੰਗਲ
sky (n),ਅਸਮਾਨ
plant (n),ਪੌਦਾ
wind (n),ਹਵਾ
soil/earth (n),ਮਿੱਟੀ
flower,ਫੁੱਲ
valley (n),ਵਾਦੀ
root (n),ਜੜ੍ਹ ?
lake (n),ਝੀਲ
star (n), ਤਾਰਾ
grass (n),ਘਾਹ
leaf (n),ਪੱਤਾ
air,ਹਵਾ
sand (n),ਰੇਤ
beach,ਬੀਚ or ਸਮੂਨਦਰ ਦੈ ਕੀਨਾਰੇ
wave [ocean],ਲਹਿਰ
fire (n),ਅੱਗ
ice (n),ਬਰਫ਼
island (n),ਟਾਪੂ
heat (n),ਗਰਮੀ
nature (n),ਕੁਦਰਤ

* ਗਿਣਤੀ (numbers)
zero (num) ਸਿਫ਼ਰ
one (num), ਇਕ ik :lpssme:
two (num), ਦੋ do :ff625:lpssme:
three (num), ਿਤੰਨ tiṇn :ff625:lpssme:
four (num), ਚਾਰ cār :ff625:lpssme:
five (num), ਪੰਜ paṇj :ff625:lpssme:
six (num), ਛੇ che :ff625:lpssme:
seven (num), ਸੱਤ satt :ff625:lpssme:
eight, ਅੱਠ āṭhṭh :ff625:lpssme:
nine (num), ਨੌਂ nauṇ :ff625:lpssme:
ten (num), ਦਸ das :ff625:lpssme:
eleven (num), ਗਿਆਰਾਂ giārāṇ :lpssme:
twelve (num), ਬਾਰਹਾਂ bārhāṇ :lpssme:
thirteen (num), ਤੇਰਾਂ
fourteen (num), ਚੌਦਾਂ
fifteen (n),ਪੰਦਰਾਂ
sixteen (num), ਸੋਲ੍ਹਾਂ
seventeen (num), ਸਤਾਰਾਂ
eighteen,ਅਠਾਰਾ
nineteen (num),ਉੱਨੀ
twenty (num),ਵੀਹ
# twenty-one (etc) **
thirty (num),ਤੀਹ
forty (num),ਚਾਲੀ
fifty (a),ਪੰਜਾਹ
sixty (num),ਸੱਠ
seventy (num), ਸੱਤਰ
eighty (n),ਅੱਸੀ
ninety (num),ਨੱਬੇ
hundred (n),ਸੌ
thousand (num),ਹਜ਼ਾਰ
million (n),ਦਸ ਲੱਖ
billion,ਅਰਬ

first (a),ਪਹਿਲਾ pahilā :ff625:lpssme:
other/second, ਦੂਜਾ dūjā :lpssme:
other/second, ਦੂਸਰਾ dūsrā :lpssme: ** huh?
third (3rd),ਤੀਜਾ
fourth,ਚੌਥੇ
fifth (a),ਪੰਜਵਾਂ
number (n),ਗਿਣਤੀ

* people
son (n), ਪੁੱਤਰ
daughter (n),ਧੀ
mother (n),ਮਾਤਾ
father,ਪਿਉ
parent (n),ਮਾਪੇ  ??
baby,ਬੱਚਾ
man (n),ਆਦਮੀ
woman (n),ਔਰਤ
brother,ਭਰਾ
sister (n),ਭੈਣ
family (n),ਪਰਿਵਾਰ
grandfather,ਦਾਦਾ ** father's father
grandmother,ਦਾਦੀ ** father's mother
grandfather
grandmother
husband (n),ਪਤੀ
wife (n),ਪਤਨੀ
king (n),ਰਾਜਾ
queen (n),ਰਾਣੀ
president (n),ਰਾਸ਼ਟਰਪਤੀ
neighbor (n),ਗੁਆਂਢੀ
boy,ਮੁੰਡਾ
girl (n),ਕੁੜੀ
child,ਬੱਚੇ
adult,ਬਾਲਗ
human (n),ਮਨੁੱਖ
friend(s) (n), ਦੋਸਤ dost :ff625:lpssme:
victim (n),ਪੀੜਤ  ???
player (n),ਖਿਡਾਰੀ
fan [sports] (n),ਪੱਖਾ
crowd (n),ਭੀੜ
person (n),ਵਿਅਕਤੀ

* pronouns
i (pn), ਮੈਂ maiṇ :ff625:lpssme: ^^
you, ਤੁਸੀਂ tusī :ff625:lpsme:
he/she/they/that, ਉਹ uh :lpssme: **
he,ਉਹ
she (pn), ਉਹ
it (p),ਇਹ
we, ਅਸੀਂāsīṇ :ff625:lpssme:
they (pn) ਉਹ  **

my, ਮੇਰਾ mairā :lpssme:
his/her, ਉਸ ਦਾ us dā :lpssme:
your, ਤੁਹਾਡਾ tuhāḍhā :lpssme:
our, ਸਾਡਾ sāḍhā :lpssme:
their, ਉਹਨਾਂ ਦਾ uhnāṇ dā :lpssme:

to me, ਮੈਨੂੰ mainūṇ :lpssme:
to us, ਸਾਨੂੰ sānūṇ :lpssme:
to you, ਤੁਹਾਨੂੰ tuhānūṇ :lpssme:

* ਮੌਸਮ (seasons)
season (n), ਮੌਸਮ
winter (n),ਸਰਦੀ
spring [season] (n),ਬਸੰਤ
summer (n),ਗਰਮੀ
fall (n),ਪਤਝੜ   # autumn

* society
religion (n),ਧਰਮ
heaven (n),ਸਵਰਗ
hell (n),ਨਰਕ
death (n),ਮੌਤ
medicine (n),ਦਵਾਈ
money, ਪੈਸਾ paisā :ff625:lpssme:
dollar (n),ਡਾਲਰ
bill (n),ਬਿੱਲ or ਨੋਟ
marriage (n),ਵਿਆਹ
wedding (n),ਵਿਆਹ
team (n),ਟੀਮ
race (ethnicity) ?? **
sex (n) [gender], ਲਿੰਗ
sex (n) [the act], ਸੈਕਸ  ??
murder (n),ਕਤਲ
prison (n),ਜੇਲ੍ਹ
technology (n),ਤਕਨਾਲੋਜੀ ??
energy (n),ਊਰਜਾ
war (n),ਜੰਗ
peace (n),ਸ਼ਾਂਤੀ
attack (n),ਹਮਲਾ
election (n),ਚੋਣ
magazines (n), ਰਸਾਲੇ rasāle :ff625:lpssme:
newspaper (n),ਅਖ਼ਬਾਰ
poison (n),ਜ਼ਹਿਰ
gun (n),ਬੰਦੂਕ
sport (n),ਖੇਡ
race (sport),ਦੌੜ
exercise (n),ਕਸਰਤ
ball,ਬਾਲ or ਗੇੰਢ
game (n),ਗੇਮ
price (n), ਕੀਮਤ kīmat :ff625:lpssme:
contract (n),ਇਕਰਾਰਨਾਮਾ
drug (n),ਦਵਾਈ
sign (n),ਨਿਸ਼ਾਨੀ ??
science (n),ਵਿਗਿਆਨ
god,ਰੱਬ ^^

* time
year (n),ਸਾਲ
month (n),ਮਹੀਨੇ
week (n),ਹਫ਼ਤੇ
day (n),ਦਿਨ
hour (n),ਘੰਟਾ
minute (n),ਮਿੰਟ
second [time],ਸਕਿੰਟ
morning (n),ਸਵੇਰੇ
afternoon,ਦੁਪਹਿਰ
evening (n),ਸ਼ਾਮ
night (n),ਰਾਤ
time (n),ਸਮਾਂ

* ਆਵਾਜਾਈ (transportation)
train (n),ਟ੍ਰੇਨ
plane (n),ਜਹਾਜ਼
car (n), ਗੱਡੀ gaḍḍī :ff625:lpssme:
truck (n),ਟਰੱਕ
bicycle,ਸਾਈਕਲ
bus,ਬੱਸ
boat,ਕਿਸ਼ਤੀ
ship (n),ਜਹਾਜ਼
tire [of a car] (n), ਟਾਇਰ
gasoline (n),ਪੈਟਰੋਲ
engine (n),ਇੰਜਨ
ticket [train] (n), ਟਿਕਟ ??
transportation (n),ਆਵਾਜਾਈ

* ਕ੍ਰਿਆਵਾਂ (verbs)
work (v), ਕੰਮ ਕਰਨਾ kaṇm karnā :ff625:lpssme:
play (v),ਖੇਡਣਾ
walk (v), ਤੁਰਨਾ turṇā :ff625:lpssme:
run (v),ਚੱਲ ਰਿਹਾ | ਦੌੜਨਾ  ??
drive (v), ਚਲਾਉਣਾ chalāuṇā :ff625:lpssme:
fly (v),ਉਡਾਣ
swim (v),ਤੈਰਨ
go (v),ਜਾਣਾ
stop (v),ਰੋਕਣਾ
follow (v),ਦੀ ਪਾਲਣਾ ਕਰਨ ਲਈ
think (v), ਸੋਚਣਾ socṇā :ff625:lpssme:
to say (v),ਕਹਿਣ ??
to speak (v), ਬੋਲਣਾ bolṇā :lpssme:
eat (v), ਖਾਣਾ khāṇā :ff625:lpssme:
drink (v), ਪੀਣਾ pīṇā :ff625:lpssme:
kill (v),ਮਾਰਨ ਲਈ
die (v),ਮਰਨਾ
smile (v),ਮੁਸਕਾਊਣਾ
laugh (v),ਹੱਸਣਾ
cry (v),ਰੋਣਾ
buy (v), ਖ਼ਰੀਦਣਾ kharīdṇā :ff625:lpssme:
pay (v), ਵੇਤਨ ?
sell (v),ਵੇਚਣਾ
shoot (v) [a gun], ਸ਼ੂਟ ਕਰਨ
learn (v), ਸਿੱਖਣਾ sikhkhaṇā :ff625:lpssme:
jump (v),ਛਾਲ ਮਾਰਕੇ # ?? jump over
smell (v),ਗੰਧ ਕਰਨ # ** but is this to smell something or to smell like something?
hear (v),ਸੁਣਨ ਲਈ
listen/hear (v), ਸੁਣਨਾ suṇnā :ff625:lpssme:
taste (v) ਚੱਖਣਾ
touch (v),ਛੋਹਣਾ
see (v), ਦੇਖਣਾ dekhṇā :ff625:lpssme:
watch (v) [ex: watch tv],ਦੇਖ ਰਹੇ ਹੋ  # ?? google: watching tv -> ਟੀਵੀ ਦੇਖਣਾ
kiss (v),ਚੁੱਮਣੀ
burn (v),ਸਾੜ
melt (v),ਪਿਘਲਣ
dig (v),ਪੁੱਟਣਾ
explode (v),ਵਿਸਫੋਟ
sit (v),  ਬੈਠਣਾ baiṭhṇā :ff625:lpssme:
stand (v),ਖੜ੍ਹਾ
love (v), ਪਿਆਰ ਕਰਨਾ  piār karnā :ff625:lpssme:
pass (v),ਪਾਸ ਕਰਨਾ
cut (v),ਕੱਟਣਾ
fight (v),ਲੜਨਾ
lie down (v),ਨਿਰਧਾਰਤ ਕਰਣਾ
dance (v),ਨੱਚਣਾ
sleep (v), ਸੌਣਾ sauṇā :ff625:lpssme:
wake up (v),ਜਾਗਣਾ
sing (v), ਗਾਉਣਾ gāuṇā :ff625:lpssme:
count (v),ਗਿਣਨ ਲਈ
marry (v),ਵਿਆਹ ਕਰਵਾਓ ??
pray (v),ਅਰਦਾਸ ਕਰੋ
win (v),ਜਿੱਤਣ
lose [vs win] (v), ਗੁਆਉਣਾ guāuṇā :ff625:lpssme:
lose [an object] (v), ??
mix/stir (v),ਰਲਾਉਣ
bend (v),ਮੋੜ
wash (v),ਧੋਣੇ
cook (v),ਪਕਾਉਣ
open (v), ਖੋਲਹਣਾ kholhṇā :ff625:lpssme:
close (v),ਬੰਦ ਕਰਨਾ
write (v), ਿਲਖਣਾ likhṇā :lpssme:
call/summon, ਬੁਲਾਉਣਾ bulāuṇā :lpssme:
turn (v),ਮੁੜਣਾ
build (v),ਬਾਣਾਉਣ
teach (v), ਿਸਖਾਉਣਾ sikhāuṇā :lpssme:
grow (v),ਵਧਣਾ
draw (v),ਸਕੈਚ ਕਰਨ ਲਈ  # to make a sketch
feed (v),ਖਿਲਾਉਣਾ
catch (v), ਫੜ੍ਹਨ  #  ਕੈਚ
throw (v),ਸੁੱਟਣਾ
clean (a),ਸਾਫ਼
find (v), ਲੱਭਣਾ labhbhaṇā :ff625:lpssme:
fall (v),ਡਿਗਣਾ
push (v),ਧੱਕਾ
pull (v),ਖਿੱਚਣ
carry (v),ਚੁਕਣਾ # pick up
break (v),ਤੋੜਨਾ
wear [clothes] (v),ਪਹਿਨਣ # ?? gt
hang (v),ਲਟਕਣ
shake (v) ਹਿਲਾਓ  ??gt
sign (v),ਸਾਈਨ ਕਰਨ ??
beat (v),ਨਾਲ ਹਰਾਇਆ  # ??
lift (v),ਉਤਰਨਾ


* ( other )
about, ਬਾਰੇ bāre :lpssme:
achieve/put on, ਪਾਉਣਾ pāuṇā :lpssme:
all, ਸਾਰਾ sārā :lpssme:
am/are, ਹਾਂ :lpssme:
and, ਅਤੇ or ਤੇ āte or te :lpssme:
answer (v), ਜਵਾਬ ਦੇਣਾ  jawāb deṇā :lpssme:
answer(s) (n), ਜਵਾਬ :lpssme:
appreciate (v), ਕਦਰ ਕਰਨੀ  kadar karnī :lpssme:
are, ਹਨ han :lpssme:
are, ਹੋ ho :lpssme:
ask, ਪੁੱਛਣਾ puchchaṇā :lpssme:
attack (v),ਹਮਲੇ **
bathroom,ਬਾਥਰੂਮ or ਗੂਸਲਖਾਨਾ
because, ਿਕਉਂ ਿਕ kiuṇki :lpssme:
become, ਬਣਨਾ baṇnā :lpssme:
begin/start, ਸ਼ੁਰੂ ਕਰਨਾ shurū karna :lpssme:
below,ਹੇਠਾਂ
books, ਕਿਤਾਬਾਂ kitābāṇ :lpssme:
bring, ਲਿਆਉਣਾ liāuṇā :lpssme:
but, ਪਰ par :lpssme:
can, / to be able ਸਕਣਾ sakṇā :lpssme:
cars, ਗੱਡੀਆਂ gaḍḍīāṇ :lpssme:
chairs, ਕੁਰਸੀਆਂ kursiāṇ :lpssme:
change (v), ਬਦਲਣਾ badalṇā :lpssme:
chimes/o’clock, ਵਜੇ waje :lpssme:
clean (v),ਸਾਫ਼ ਕਰਨ ਲਈ
come out, ਿਨਕਲਣਾ nikalṇā :lpssme:
come, ਆਉਣਾ āuṇā :lpssme:
decide, ਫ਼ੈਸਲਾ ਕਰਨਾ faisalā karna :lpssme:
different, ਵੱਖਰਾ wakhkharā :lpssme:
doors, ਦਰਵਾਜੇ darvāje :lpssme:
dress (v),ਕੱਪੜੇ ਪਾ ਲਉ   # to get dressed
easy, ਸੌਖਾ saukhā :lpssme:
english, ਅੰਗਰੇਜ਼ੀ aṇgrezī :lpssme: ^^
enjoy (v), ਆਨੰਦ ਮਾਣਨਾ ānaṇd māṇnā :lpssme:
explain (v), ਸਮਝਾਉਣਾ samjhāuṇā :lpssme:
fall (rain or snow) (v), ਪੈਣਾ paiṇā :lpssme: **
fat, ਮੋਟਾ moṭā :lpssme:
finish (v), ਖਤਮ ਕਰਨਾ khatam karna :lpssme:
for, ਲਈ laī :lpssme:
from, ਤੋਂ toṇ :lpssme:
give (v), ਦੇਣਾ deṇā :lpssme:
have/must (v), ਪੈਣਾ paiṇā :lpssme: **  # same as word for rain/now fall
help (v), ਮਦਦ ਕਰਨੀ madad karnī :lpssme:
hill (n),ਪਹਾੜੀ
how much/many, ਕਿੰਨਾ kiṇnā :lpssme:
how ਕਿਵੇਂ kiweṇ, :lpssme:
if, ਜੇ je :lpssme:
important, ਮਹੱਤਵਪੂਰਣ mahattawpūaṇ :lpssme:
in, ਵਿੱਚ wicc :lpssme:
interesting, ਿਦਲਚਸਪ dilcasp :lpssme:
is, ਹੈ hai :lpssme:
know (v), ਜਾਣਨਾ jāṇnā :lpssme:
letters, ਚਿੱਠੀਆਂ ciṭhṭhīāṇ :lpssme:
little (a),ਨਿੱਕਾ :mjw: # little kid/young?
make (v), ਬਣਾਉਣਾ banāuṇā :lpssme:
meet (v), ਮਿਲਣਾ milṇā :lpssme:
necessary, ਜ਼ਰੂਰੀ zarūrī :lpssme:
next, ਅਗਲਾ āgalā :lpssme:
not, ਨਹੀਂ nahīṇ :lpssme:
of, ਦਾ dā :lpssme:
on, ਉੱਤੇ utte :lpssme:
pathway(s), ਰਾਹ rāh :lpssme:
picture, ਤਸਵੀਰ taswīr :lpssme:
pictures, ਤਸਵੀਰਾਂ taswīrāṇ :lpssme:
planet (n), ਗ੍ਰਹਿ
promise (v), ਵਾਅਦਾ ਕਰਨਾ wādā karnā :lpssme:
punjabi, ਪੰਜਾਬੀ paṇjābī :lpssme: ^^
put/keep (v), ਰੱਖਣਾ rakhkhaṇā :lpssme:
question(s), ਸਵਾਲ sawāl :lpssme:
read (v), ਪੜਹਨਾ par̥hnā :lpssme:
reason(s), ਕਾਰਨ kāran :lpssme:
remember (v), ਯਾਦ ਰੱਖਣੀ yād rakhkhaṇī :lpssme:
remind (v), ਯਾਦ ਕਰਾਉਣੀ yād karāuṇī :lpssme:
save/rescue (v), ਬਚਾਉਣਾ bachāuṇā :lpssme:
scream (v),ਚੀਕਣ
second [2nd],ਦੂਜਾ
shop (n), ਦੁਕਾਨ dukān :lpssme:
should/ought, ਚਾਹੀਦਾ cāhīdā :lpssme:
show (v), ਿਦਖਾਉਣਾ dikhāuṇā :lpssme:
silence, ਚੁੱਪ cupp :lpssme:
so that, ਤਾਂਿਕ tāṇki :lpssme:
stories, ਕਹਾਣੀਆਂ kahāṇīāṇ :lpssme:
story, ਕਹਾਣੀ kahāṇī :lpssme:
straight [vs crooked], ਸਿੱਧਾ ?? # same as direction
take/receive (v), ਲੈਣਾ laiṇā :lpssme:
tell (v), ਦੱਸਣਾ dassaṇā :lpssme:
that, ਿਕ ki :lpssme:
then, ਤਾਂ tāṇ :lpssme:
tiny/little, ਥੋੜਹਾ thor̥hā :lpssme:
to, ਨੂੰ nūṇ :lpssme:
try (v), ਕੋਿਸ਼ਸ਼ ਕਰਨੀ koshish karnī :lpssme:
understand (v), ਸਮਝਣਾ samajhṇā :lpssme:
until/up to, ਤਕ tak :lpssme:
use (v), ਵਰਤਣਾ waratṇā :lpssme:
very (Invariable), ਬਹੁਤ bahut :lpssme:
want (v), ਚਾਹੁਣਾ cāhuṇā :lpssme:
wave [hand] (v),ਅਲਵਿਦਾ ਕਰਨ # ??
what, ਕੀ kī :lpssme:
when, ਕਦੋਂ kadoṇ :lpssme:
when, ਜਦੋਂjadoṇ :lpssme:
where, ਕਿਥੇ kithe :lpssme:
which, ਕਿਹੜਾ kihr̥ā :lpssme:
who, ਕੌਣ kauṇ :lpssme:
why, ਕਿਉਂ kiuṇ :lpssme:
with, ਨਾਲ nāl :lpssme:
word (n),ਸ਼ਬਦ
work (n), ਕੰਮ kaṇm :lpssme:
